name: tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - 'tools/**'
  pull_request:
    paths-ignore:
      - README.md
      - 'tools/**'

jobs:
  lint-and-pytest:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: python setup.py install
    - run: pip install flake8 isort -r test/requirements.txt
    - run: flake8
    - run: pytest -s test/
    - run: isort .
